[server]
host = "127.0.0.1"
port = 8080
max_connections = 1000

[database]
path = "nostr_relay.db"
max_connections = 10

[limits]
max_event_size = 16384
max_events_per_request = 1000
max_filters_per_subscription = 10
max_subscriptions_per_connection = 10
rate_limit_events_per_second = 100

[relay]
name = "nostr-rs-indexer"
description = "A NOSTR indexer implementation in Rust"
pubkey = ""
contact = ""
supported_nips = [1, 11, 42]
software = "nostr-rs-indexer"
version = "0.1.0"

[indexer]
relay_urls = [
    "wss://relay.damus.io",
    "wss://nos.lol",
    "wss://relay.snort.social",
    "wss://nostr.wine",
    "wss://eden.nostr.land",
    "wss://relay.primal.net"
]
index_interval_seconds = 300
max_events_per_index = 1000
enable_profile_indexing = true
enable_relationship_indexing = true
